### ISSUE TITLE
WriteBulks(nil) does not return a nil array

### ISSUE THREAD

**Issue by agis** [secmask/go-redisproto#4]
The following path can never be executed: https://github.com/secmask/go-redisproto/blob/14323b204640af1628764b06726c64fe040998e1/writer.go#L127-L130

...since when doing `writer.WriteBulks(nil)`, the `bulks` variable ends up being a  `[][]uint8{[]uint8(nil)}`, which is not equal to nil.

The same holds true for `WriteObjects` as well. On the other hand, doing `WriteBulkStrings(nil)` does produce a nil array (`[]byte{'*', '-', '1', '\r', '\n'}`).

**Comment by secmask** [comment]
that's correct, while `WriteBulks` and `WriteObjects` implement using variadic args, WriteBulkStrings uses `[]string` 

so `WriteBulks(nil)` and `WriteObjects(nil)` mean response an array with 1 element(nil),   `WriteBulks()` will actually write nil array response instead.
I understand that it would make confuse here, my idea when make it like this is
- variadic useful when we have a fix list of vars to response, say we have var `intX`, `strY` to response with `WriteObjects`, it will be `WriteObjects([]interface{}{intX, strY})` vs `WriteObjects(intX, strY)`, I prefer the later, so I make it as variadic instead of `WriteObjects([]interface{})`
- `WriteBulkStrings` accept `[]string` because if we have a fix list of vars, just use WriteObjects version, other wise when we have a slice as args match here.

so turn back to your issue, I see the trouble here, I'm seeking for a way to make it better and less breaking thing

**Comment by secmask** [comment]
I can add `WriteObjectSlice([]interface{})` and `WriteBulkSlice([][]byte)` version if it helps your situation, seem that way won't break anything

**Comment by agis** [comment]
This seems a good solution. Minor: I'd name these methods `WriteObjectsSlice` and `WriteBulksSlice`.

**Comment by secmask** [comment]
I pushed a commit https://github.com/secmask/go-redisproto/commit/7963d3e44e330702c8e82393b4aec88a2fa1836d, take a looks if it works for you.

**Comment by agis** [comment]
Thanks!
